name: Prettier

on: [pull_request]

jobs:
  format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install yarn
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
        export PATH=$HOME/.yarn/bin:$PATH
    - name: install dependencies and format
      run: |
        yarn
        yarn format
      env:
        CI: true
    - name: commit changes
      run: |
        git config --global user.name 'Haroenbot'
        git config --global user.email 'spam@haroen.me'
        git add -A && git commit -m 'chore(prettier): format code' --allow-empty
        git push -u origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
