name: Prettier

on: [pull_request]

jobs:
  format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: install yarn
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
        export PATH=$HOME/.yarn/bin:$PATH

    - name: install dependencies and format
      run: |
        yarn
        yarn format
      env:
        CI: true

    - name: run if git status is different
      if: git diff-files --quiet
      run: echo lol this runs

    # - name: commit changes
    #   run: |
    #     git config --global user.name 'Haroenbot'
    #     git config --global user.email 'spam@haroen.me'
    #     git checkout ${{ github.head_ref }}
    #     git add -A && git commit -m 'chore(prettier): format code' --allow-empty
    #     git push https://${GITHUB_PUSH_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY} ${{ github.head_ref }}
    #   env:
    #     GITHUB_PUSH_TOKEN: ${{ secrets.GITHUB_PUSH_TOKEN }}
